In [1]:
import numpy as np
import pandas as pd
V1 = np.array([1,3,6,np.NaN,7,1,np.NaN,9,15])
V2 = np.array([7,np.NaN,5,8,12,np.NaN,np.NaN,2,3])
V3 = np.array([np.NaN,12,5,6,14,7,np.NaN,2,31])
df= pd.DataFrame(
        {"V1" : V1,
         "V2" : V2,
         "V3" : V3}
)
df

     V1    V2    V3
0   1.0   7.0   NaN
1   3.0   NaN  12.0
2   6.0   5.0   5.0
3   NaN   8.0   6.0
4   7.0  12.0  14.0
5   1.0   NaN   7.0
6   NaN   NaN   NaN
7   9.0   2.0   2.0
8  15.0   3.0  31.0

In [2]:
#sayısal değişkenler atama

In [3]:
df['V1'].fillna(df['V1'].mean())

0     1.0
1     3.0
2     6.0
3     6.0
4     7.0
5     1.0
6     6.0
7     9.0
8    15.0
Name: V1, dtype: float64

In [4]:
df.apply(lambda x: x.fillna(x.mean()), axis=0)

     V1         V2    V3
0   1.0   7.000000  11.0
1   3.0   6.166667  12.0
2   6.0   5.000000   5.0
3   6.0   8.000000   6.0
4   7.0  12.000000  14.0
5   1.0   6.166667   7.0
6   6.0   6.166667  11.0
7   9.0   2.000000   2.0
8  15.0   3.000000  31.0

In [5]:
df.fillna(df.mean()[:])

     V1         V2    V3
0   1.0   7.000000  11.0
1   3.0   6.166667  12.0
2   6.0   5.000000   5.0
3   6.0   8.000000   6.0
4   7.0  12.000000  14.0
5   1.0   6.166667   7.0
6   6.0   6.166667  11.0
7   9.0   2.000000   2.0
8  15.0   3.000000  31.0

In [6]:
df.fillna(df.mean()["V1":"V3"])

     V1         V2    V3
0   1.0   7.000000  11.0
1   3.0   6.166667  12.0
2   6.0   5.000000   5.0
3   6.0   8.000000   6.0
4   7.0  12.000000  14.0
5   1.0   6.166667   7.0
6   6.0   6.166667  11.0
7   9.0   2.000000   2.0
8  15.0   3.000000  31.0

In [7]:
df["V3"].fillna(df["V3"].median())

0     7.0
1    12.0
2     5.0
3     6.0
4    14.0
5     7.0
6     7.0
7     2.0
8    31.0
Name: V3, dtype: float64

In [9]:
df.where(pd.notna(df), df.mean(), axis='columns')

     V1         V2    V3
0   1.0   7.000000  11.0
1   3.0   6.166667  12.0
2   6.0   5.000000   5.0
3   6.0   8.000000   6.0
4   7.0  12.000000  14.0
5   1.0   6.166667   7.0
6   6.0   6.166667  11.0
7   9.0   2.000000   2.0
8  15.0   3.000000  31.0

**Kategorik Değişken Kırılımında Değer Atama**

In [13]:
V1= np.array([1,3,6,np.NaN,7,1,np.NaN,9,15])
V2= np.array([7, np.NaN, 5, 8, 12, np.NaN, np.NaN, 2, 3])
V3= np.array([np.NaN, 12, 5, 6, 14, 7, np.NaN, 2, 31])
v4= np.array(["IT","IT","IK","IK","IK","IK","IK","IT","IT"], dtype=object)
df= pd.DataFrame(
        {"maas" : V1,
         "V2" : V2,
         "V3" : V3,
         "departman" : v4}
)
df

   maas    V2    V3 departman
0   1.0   7.0   NaN        IT
1   3.0   NaN  12.0        IT
2   6.0   5.0   5.0        IK
3   NaN   8.0   6.0        IK
4   7.0  12.0  14.0        IK
5   1.0   NaN   7.0        IK
6   NaN   NaN   NaN        IK
7   9.0   2.0   2.0        IT
8  15.0   3.0  31.0        IT

In [14]:
df.groupby("departman")["maas"].mean()

departman
IK    4.666667
IT    7.000000
Name: maas, dtype: float64

In [15]:
df["maas"].fillna(df.groupby("departman")["maas"].transform("mean"))

0     1.000000
1     3.000000
2     6.000000
3     4.666667
4     7.000000
5     1.000000
6     4.666667
7     9.000000
8    15.000000
Name: maas, dtype: float64

**Kategorik Değişkenler için Eksik Değer Atama**

In [16]:
V1= np.array([1,3,6,np.NaN,7,1,np.NaN,9,15])
v4= np.array(["IT", np.NaN,"IK","IK","IK","IK","IK","IT","IT"], dtype=object)
df= pd.DataFrame(
        {"maas" : V1,
         "departman" : v4}
)
df

   maas departman
0   1.0        IT
1   3.0       NaN
2   6.0        IK
3   NaN        IK
4   7.0        IK
5   1.0        IK
6   NaN        IK
7   9.0        IT
8  15.0        IT

In [17]:
df["departman"].fillna(df["departman"].mode()[0])

0    IT
1    IK
2    IK
3    IK
4    IK
5    IK
6    IK
7    IT
8    IT
Name: departman, dtype: object

In [19]:
df["departman"].fillna(method="bfill")#kendinden sonra gelenle doldurulur

<ipython-input-19-caeffb751821>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["departman"].fillna(method="bfill")#kendinden sonra gelenle doldurulur

0    IT
1    IK
2    IK
3    IK
4    IK
5    IK
6    IK
7    IT
8    IT
Name: departman, dtype: object

In [20]:
df['departman'].fillna(method='ffill')#kendinden önce gelenle doldurulur

<ipython-input-20-565269342bbe>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['departman'].fillna(method='ffill')#kendinden önce gelenle doldurulur

0    IT
1    IT
2    IK
3    IK
4    IK
5    IK
6    IK
7    IT
8    IT
Name: departman, dtype: object

**Tahmine dayalı değer atama yöntemleri**

In [33]:
import seaborn as sns
df= sns.load_dataset('titanic')
df= df.select_dtypes(include=['float64','int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [22]:
!pip install ycimpute

Collecting ycimpute
  Downloading ycimpute-0.2-py3-none-any.whl.metadata (775 bytes)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from ycimpute) (1.17.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.11/dist-packages (from ycimpute) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from ycimpute) (1.13.1)
Requirement already satisfied: scikit-learn>=0.17.1 in /usr/local/lib/python3.11/dist-packages (from ycimpute) (1.6.0)
Requirement already satisfied: torch>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from ycimpute) (2.5.1+cu121)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.17.1->ycimpute) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.17.1->ycimpute) (3.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.1.0->ycimpute) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.1.0->ycimpute) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.1.0->ycimpute) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.1.0->ycimpute) (3.0.2)
Downloading ycimpute-0.2-py3-none-any.whl (35 kB)
Installing collected packages: ycimpute
Successfully installed ycimpute-0.2

In [23]:
from ycimpute.imputer import knnimput

In [24]:
var_names= list(df)

In [35]:
n_df = np.array(df)

In [36]:
n_df[:10]

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [27]:
n_df.shape

(891, 6)

In [37]:
ddf = knnimput.KNN(k=4).complete(n_df)

Imputing row 1/891 with 0 missing, elapsed time: 0.184
Imputing row 101/891 with 0 missing, elapsed time: 0.187
Imputing row 201/891 with 0 missing, elapsed time: 0.189
Imputing row 301/891 with 1 missing, elapsed time: 0.190
Imputing row 401/891 with 0 missing, elapsed time: 0.191
Imputing row 501/891 with 0 missing, elapsed time: 0.193
Imputing row 601/891 with 0 missing, elapsed time: 0.194
Imputing row 701/891 with 0 missing, elapsed time: 0.196
Imputing row 801/891 with 0 missing, elapsed time: 0.198

In [39]:
type(ddf)

numpy.ndarray

In [40]:
dff = pd.DataFrame(ddf, columns=var_names)

In [41]:
type(dff)

pandas.core.frame.DataFrame

In [42]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

In [43]:
#random forest
import seaborn as sns
df= sns.load_dataset('titanic')
df= df.select_dtypes(include=['float64','int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [44]:
df.isnull().sum()

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [45]:
var_names= list(df)

In [46]:
n_df = np.array(df)

In [67]:
from sklearn.experimental import enable_iterative_imputer  # Gerekli
from sklearn.impute import IterativeImputer

# IterativeImputer ile eksik değerleri doldurma
imputer = IterativeImputer(random_state=42)
dff = imputer.fit_transform(n_df)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  # that has no feature names.
/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The IterativeImputer or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  # that has no feature names.
/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SimpleImputer or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The SimpleImputer or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  # that has no feature names.

In [68]:
dff = pd.DataFrame(dff, columns=var_names)

In [69]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

In [70]:
#EM
import seaborn as sns
df= sns.load_dataset('titanic')
df= df.select_dtypes(include=['float64','int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [71]:
from ycimpute.imputer import EM

In [72]:
var_names= list(df)
n_df = np.array(df)

In [73]:
dff = EM().complete(n_df)

In [74]:
dff = pd.DataFrame(dff, columns=var_names)

In [75]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64